# Generated by Django 4.2.1 on 2023-05-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoanAppModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.PositiveIntegerField()),
                ('open_status', models.BooleanField()),
                ('initial_loan_amnt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_installments', models.IntegerField()),
                ('amt_per_installments', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amt_left', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'loan_app',
            },
        ),
    ]
