# Generated by Django 4.2.1 on 2023-05-30 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_id', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Submitted', 'Submitted'), ('Rejected', 'Rejected'), ('Open', 'Open'), ('Closed', 'Closed')], default='Submitted', max_length=15)),
                ('initial_loan_amnt', models.DecimalField(decimal_places=2, max_digits=6)),
                ('num_installments', models.IntegerField()),
                ('amt_per_installments', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_amt_left', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
            options={
                'verbose_name': 'loan_app',
            },
        ),
        migrations.DeleteModel(
            name='LoanAppModel',
        ),
    ]
