# Generated by Django 4.2.1 on 2023-05-30 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_loanmodel_delete_loanappmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanmodel',
            name='amt_per_installments',
        ),
    ]
