# Generated by Django 4.2.1 on 2023-05-30 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_loanmodel_amt_per_installments'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanmodel',
            name='amt_per_installment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
